import type { ThemePreset } from "../types.js";

export const cyberpunkTheme: ThemePreset = {
  id: "cyberpunk",
  label: "Cyberpunk",
  description: "Blackout shell with electric blue, violet, and hot-pink neon accents.",
  source: "core",
  mode: "dark",
  tightness: "tight",
  surfaceHierarchy: "soft",
  tokens: {
    background: "#030308",
    foreground: "#F6F2FF",
    card: "#0A0912",
    "card-foreground": "#F6F2FF",
    popover: "#0D0B16",
    "popover-foreground": "#F6F2FF",
    sidebar: "#070712",
    "sidebar-foreground": "#DCCBFF",
    topbar: "#080812",
    "topbar-foreground": "#FBF8FF",
    muted: "#151225",
    "muted-foreground": "#AF9DCB",
    border: "#34274D",
    input: "#120F1D",
    primary: "#F3EE72",
    "primary-foreground": "#141000",
    secondary: "#171329",
    "secondary-foreground": "#E7DBFF",
    accent: "#46CFFF",
    "accent-foreground": "#02141D",
    danger: "#FF5B84",
    "danger-foreground": "#24020C",
    success: "#41E6D2",
    "success-foreground": "#021412",
    warning: "#FFB35C",
    "warning-foreground": "#2A1200",
    positive: "#41E6D2",
    negative: "#FF5B84",
    ring: "#8F63FF",
    "chart-grid": "#3AA8D8",
    radius: "16px",
  },
};
