import type { ThemePreset } from "../types.js";

export const draculaTheme: ThemePreset = {
  id: "dracula",
  label: "Dracula",
  description: "Dracula-inspired dark theme with violet surfaces, electric cyan accents, and warm status tones.",
  source: "core",
  mode: "dark",
  tightness: "tight",
  surfaceHierarchy: "soft",
  tokens: {
    background: "#282A36",
    foreground: "#F8F8F2",
    card: "#303341",
    "card-foreground": "#F8F8F2",
    popover: "#303341",
    "popover-foreground": "#F8F8F2",
    sidebar: "#21222C",
    "sidebar-foreground": "#F8F8F2",
    topbar: "#21222C",
    "topbar-foreground": "#F8F8F2",
    muted: "#44475A",
    "muted-foreground": "#A4ACCC",
    border: "#4B5070",
    input: "#343746",
    primary: "#BD93F9",
    "primary-foreground": "#191A21",
    secondary: "#3A3D4F",
    "secondary-foreground": "#F8F8F2",
    accent: "#8BE9FD",
    "accent-foreground": "#0C1B21",
    danger: "#FF5555",
    "danger-foreground": "#FFF1F1",
    success: "#50FA7B",
    "success-foreground": "#08160B",
    warning: "#FFB86C",
    "warning-foreground": "#231404",
    positive: "#50FA7B",
    negative: "#FF5555",
    ring: "#FF79C6",
    "chart-grid": "#6272A4",
    radius: "16px",
  },
};
