import type { ThemePreset } from "../types.js";

export const grandpaTheme: ThemePreset = {
  id: "grandpa",
  label: "Grandpa",
  description: "Bloomberg-style terminal preset with dark gray chrome, amber emphasis, and utility blue highlights.",
  source: "core",
  mode: "dark",
  tightness: "tight",
  surfaceHierarchy: "framed",
  fonts: {
    sans: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
  tokens: {
    background: "#050505",
    foreground: "#D7D3C8",
    card: "#111214",
    "card-foreground": "#EFE6D4",
    popover: "#0E0F11",
    "popover-foreground": "#EFE6D4",
    sidebar: "#0A0B0D",
    "sidebar-foreground": "#D1C9B7",
    topbar: "#090A0C",
    "topbar-foreground": "#F3EAD8",
    muted: "#17181B",
    "muted-foreground": "#A99A75",
    border: "#34373C",
    input: "#131416",
    primary: "#F2A12B",
    "primary-foreground": "#1A0D00",
    secondary: "#345D9B",
    "secondary-foreground": "#E9F0FF",
    accent: "#2E7ACF",
    "accent-foreground": "#F6FAFF",
    danger: "#D94C57",
    "danger-foreground": "#FFF3F5",
    success: "#2E9D51",
    "success-foreground": "#F2FFF6",
    warning: "#D8A13A",
    "warning-foreground": "#2B1500",
    positive: "#2E9D51",
    negative: "#D94C57",
    ring: "#F2A12B",
    "chart-grid": "#45484E",
    radius: "6px",
  },
};
