import type { ThemePreset } from "../types.js";

export const graphiteTheme: ThemePreset = {
  id: "graphite",
  label: "Graphite",
  description: "Dark default terminal theme.",
  source: "core",
  mode: "dark",
  tightness: "tight",
  surfaceHierarchy: "soft",
  tokens: {
    background: "#0B1017",
    foreground: "#E6EDF7",
    card: "#121925",
    "card-foreground": "#E6EDF7",
    popover: "#141B29",
    "popover-foreground": "#E6EDF7",
    sidebar: "#0E1522",
    "sidebar-foreground": "#CBD5E1",
    topbar: "#0F1724",
    "topbar-foreground": "#F8FAFC",
    muted: "#1A2333",
    "muted-foreground": "#91A4BD",
    border: "#263449",
    input: "#1B2434",
    primary: "#4F8CFF",
    "primary-foreground": "#F8FAFC",
    secondary: "#1E293B",
    "secondary-foreground": "#E2E8F0",
    accent: "#10B981",
    "accent-foreground": "#032216",
    danger: "#EF4444",
    "danger-foreground": "#FFFFFF",
    success: "#22C55E",
    "success-foreground": "#02140A",
    warning: "#F59E0B",
    "warning-foreground": "#201400",
    positive: "#22C55E",
    negative: "#F87171",
    ring: "#4F8CFF",
    "chart-grid": "#FFFFFF",
    radius: "16px",
  },
};
