import type { ThemePreset } from "../types.js";

export const mainSequenceTheme: ThemePreset = {
  id: "main-sequence",
  label: "Sapphire",
  description: "Sapphire dark theme with branded shell gradients.",
  source: "core",
  mode: "dark",
  tightness: "tight",
  surfaceHierarchy: "soft",
  tokens: {
    background: "#0B1017",
    foreground: "#E6EDF7",
    card: "#121925",
    "card-foreground": "#E6EDF7",
    popover: "#141B29",
    "popover-foreground": "#E6EDF7",
    sidebar: "#0E1522",
    "sidebar-foreground": "#CBD5E1",
    topbar: "#0F1724",
    "topbar-foreground": "#F8FAFC",
    muted: "#1A2333",
    "muted-foreground": "#91A4BD",
    border: "#151D29",
    input: "#161F2C",
    primary: "#536DE8",
    "primary-foreground": "#F8FAFC",
    secondary: "#202A45",
    "secondary-foreground": "#E8EEFF",
    accent: "#22D3EE",
    "accent-foreground": "#0B1020",
    danger: "#EF4444",
    "danger-foreground": "#FFFFFF",
    success: "#22C55E",
    "success-foreground": "#02140A",
    warning: "#F59E0B",
    "warning-foreground": "#201400",
    positive: "#22C55E",
    negative: "#F87171",
    ring: "#536DE8",
    "chart-grid": "#FFFFFF",
    radius: "16px",
  },
};
