import type { ThemePreset } from "../types.js";

export const mainSequenceSpaceTheme: ThemePreset = {
  id: "main-sequence-space",
  label: "Main Sequence",
  description: "Main Sequence operational dark theme with blue and gold signal accents.",
  source: "core",
  mode: "dark",
  tightness: "tight",
  surfaceHierarchy: "soft",
  tokens: {
    background: "#03070E",
    foreground: "#EEF5FF",
    card: "#08111D",
    "card-foreground": "#EEF5FF",
    popover: "#0B1422",
    "popover-foreground": "#F4F8FF",
    sidebar: "#040912",
    "sidebar-foreground": "#D9E4F2",
    topbar: "#050B14",
    "topbar-foreground": "#F8FBFF",
    muted: "#101A28",
    "muted-foreground": "#9FADC3",
    border: "#172235",
    input: "#0D1725",
    primary: "#8FB7D9",
    "primary-foreground": "#03101B",
    secondary: "#142033",
    "secondary-foreground": "#E6EEFB",
    accent: "#D8A65E",
    "accent-foreground": "#1D1202",
    danger: "#FF6B8A",
    "danger-foreground": "#24020A",
    success: "#5EEAD4",
    "success-foreground": "#031514",
    warning: "#DFA85B",
    "warning-foreground": "#1E1102",
    positive: "#5EEAD4",
    negative: "#FF6B8A",
    ring: "#9FC7E8",
    "chart-grid": "#D8E8FF",
    radius: "12px",
  },
  dataViz: {
    categorical: [
      "#8FB7D9",
      "#D8A65E",
      "#F4F8FF",
      "#73C8D7",
      "#9F9AD8",
      "#C18445",
      "#788CA5",
      "#6F9FBD",
      "#B8C7D9",
      "#C08A48",
    ],
    sequential: {
      primary: {
        start: "#06111F",
        mid: "#6F9FBD",
        end: "#F4F8FF",
      },
      success: {
        start: "#051418",
        mid: "#22D3EE",
        end: "#D8F8FF",
      },
      warning: {
        start: "#171006",
        mid: "#C18445",
        end: "#D8A65E",
      },
      neutral: {
        start: "#050914",
        mid: "#70829E",
        end: "#F4F8FF",
      },
    },
    diverging: {
      default: {
        negative: "#6F9FBD",
        neutral: "#F4F8FF",
        positive: "#C18445",
      },
      "positive-negative": {
        negative: "#FF6B8A",
        neutral: "#111B2A",
        positive: "#5EEAD4",
      },
    },
  },
};
