import type { ThemePreset } from "../types.js";

export const neonMintTheme: ThemePreset = {
  id: "neon-mint",
  label: "Neon Mint",
  description: "High-contrast dark shell with mint and cyan accents.",
  source: "core",
  mode: "dark",
  tightness: "tight",
  surfaceHierarchy: "soft",
  tokens: {
    background: "#07110E",
    foreground: "#E7FFF7",
    card: "#0E1815",
    "card-foreground": "#E7FFF7",
    popover: "#11201B",
    "popover-foreground": "#E7FFF7",
    sidebar: "#091511",
    "sidebar-foreground": "#BFEFD9",
    topbar: "#0A1513",
    "topbar-foreground": "#F3FFF9",
    muted: "#15231E",
    "muted-foreground": "#84B7A2",
    border: "#1F4234",
    input: "#10211B",
    primary: "#37E8A7",
    "primary-foreground": "#051A12",
    secondary: "#123026",
    "secondary-foreground": "#D9FFF1",
    accent: "#6EE7F9",
    "accent-foreground": "#042430",
    danger: "#FB7185",
    "danger-foreground": "#FFFFFF",
    success: "#22C55E",
    "success-foreground": "#031409",
    warning: "#FACC15",
    "warning-foreground": "#2A2100",
    positive: "#37E8A7",
    negative: "#FB7185",
    ring: "#37E8A7",
    "chart-grid": "#6EE7F9",
    radius: "18px",
  },
};
