import type { ThemePreset } from "../types.js";

export const pandaTruenoTheme: ThemePreset = {
  id: "panda-trueno",
  label: "Panda",
  description:
    "AE86-inspired light theme with pearl white panels, black trim, electric blue stripe energy, and amber lamp accents.",
  source: "core",
  mode: "light",
  tightness: "tight",
  surfaceHierarchy: "framed",
  tokens: {
    background: "#F3F3EF",
    foreground: "#14171A",
    card: "#FCFCFA",
    "card-foreground": "#14171A",
    popover: "#FFFFFF",
    "popover-foreground": "#14171A",
    sidebar: "#E7E9E5",
    "sidebar-foreground": "#20242A",
    topbar: "#FCFCFA",
    "topbar-foreground": "#121518",
    muted: "#E1E5E8",
    "muted-foreground": "#5C6670",
    border: "#C6CDD5",
    input: "#EEF1F2",
    primary: "#111417",
    "primary-foreground": "#F8F9FA",
    secondary: "#2F78F2",
    "secondary-foreground": "#F8FBFF",
    accent: "#D58A2F",
    "accent-foreground": "#211200",
    danger: "#D94A49",
    "danger-foreground": "#FFF8F8",
    success: "#1F8A76",
    "success-foreground": "#F4FFFC",
    warning: "#D58A2F",
    "warning-foreground": "#231300",
    positive: "#1F8A76",
    negative: "#D94A49",
    ring: "#2F78F2",
    "chart-grid": "#242A31",
    radius: "12px",
  },
};
