import type { ThemePreset } from "../types.js";

export const quartzLightTheme: ThemePreset = {
  id: "quartz-light",
  label: "Main Sequence Light",
  description: "Clean Main Sequence light mode for admin or analyst workflows.",
  source: "core",
  mode: "light",
  tightness: "tight",
  surfaceHierarchy: "flat",
  tokens: {
    background: "#F5F7FB",
    foreground: "#152238",
    card: "#FFFFFF",
    "card-foreground": "#132032",
    popover: "#FFFFFF",
    "popover-foreground": "#132032",
    sidebar: "#ECF1F8",
    "sidebar-foreground": "#25364D",
    topbar: "#FFFFFF",
    "topbar-foreground": "#122033",
    muted: "#E8EDF6",
    "muted-foreground": "#60738F",
    border: "#D7E0EE",
    input: "#EDF2F9",
    primary: "#2563EB",
    "primary-foreground": "#FFFFFF",
    secondary: "#E2E8F0",
    "secondary-foreground": "#1E293B",
    accent: "#0EA5E9",
    "accent-foreground": "#032236",
    danger: "#DC2626",
    "danger-foreground": "#FFFFFF",
    success: "#16A34A",
    "success-foreground": "#FFFFFF",
    warning: "#D97706",
    "warning-foreground": "#FFFFFF",
    positive: "#16A34A",
    negative: "#DC2626",
    ring: "#2563EB",
    "chart-grid": "#1E293B",
    radius: "16px",
  },
};
