import type { ThemePreset } from "../types.js";

export const sakuraTheme: ThemePreset = {
  id: "sakura",
  label: "Sakura",
  description: "Soft blush light theme inspired by Light Pink with cherry-petal surfaces and rose accents.",
  source: "core",
  mode: "light",
  tightness: "tight",
  surfaceHierarchy: "soft",
  tokens: {
    background: "#FFF4F8",
    foreground: "#402638",
    card: "#FFF9FC",
    "card-foreground": "#402638",
    popover: "#FFF9FC",
    "popover-foreground": "#402638",
    sidebar: "#FBE8F1",
    "sidebar-foreground": "#553448",
    topbar: "#FFF8FB",
    "topbar-foreground": "#402638",
    muted: "#F4DEE8",
    "muted-foreground": "#8A6678",
    border: "#EBCFDA",
    input: "#F9EAF1",
    primary: "#D76497",
    "primary-foreground": "#FFF9FC",
    secondary: "#F1D5E2",
    "secondary-foreground": "#5A3448",
    accent: "#F2A7C8",
    "accent-foreground": "#57243F",
    danger: "#D95C77",
    "danger-foreground": "#FFF9FC",
    success: "#5FA48B",
    "success-foreground": "#F7FFFC",
    warning: "#D58A4A",
    "warning-foreground": "#FFF8F2",
    positive: "#5FA48B",
    negative: "#D95C77",
    ring: "#D76497",
    "chart-grid": "#C67A9F",
    radius: "20px",
  },
};
