import { spawnSync } from "node:child_process";
import {
  lstat,
  mkdir,
  readFile,
  realpath,
  readdir,
  stat,
  writeFile,
} from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

export const DOCUMENTATION_DEV_DEPENDENCIES = Object.freeze({
  "@docusaurus/core": "3.10.2",
  "@docusaurus/preset-classic": "3.10.2",
  "@mdx-js/react": "3.1.1",
  "prism-react-renderer": "2.4.1",
});

export const DOCUMENTATION_SCRIPTS = Object.freeze({
  "docs:sync": "node scripts/sync-docs-navigation.mjs",
  "docs:check":
    "node scripts/check-docs-toolchain.mjs && npm run docs:sync -- --check && node scripts/validate-docs.mjs",
  "docs:dev":
    "npm run docs:sync && docusaurus start documentation --host 127.0.0.1 --port 3011 --no-open",
  "build:docs":
    "npm run docs:sync && docusaurus build documentation --out-dir ../dist/docs",
});

const COMBINED_BUILD_SCRIPT = "npm run build:app && npm run build:docs";
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const templateRoot = join(
  packageRoot,
  "agent_scaffold",
  "skills",
  "documentation",
  "document-command-center-application",
  "assets",
  "application",
);
const ignoredDirectories = new Set([".git", "node_modules"]);
const generatedTemplateMarkers = new Map([
  [
    "docs/SUMMARY.md",
    "# Documentation\n\nThis map and the Docusaurus sidebar are generated from `documentation/navigation.json`.",
  ],
  [
    "documentation/sidebars.mjs",
    "// Generated by scripts/sync-docs-navigation.mjs. Do not edit directly.",
  ],
]);

export class ApplicationDocsInitError extends Error {
  constructor(message, { stage = "application-docs-init", applicationRoot = null, cause } = {}) {
    super(message, { cause });
    this.name = "ApplicationDocsInitError";
    this.stage = stage;
    this.applicationRoot = applicationRoot;
  }

  toJSON() {
    return {
      error: this.message,
      stage: this.stage,
      applicationRoot: this.applicationRoot,
    };
  }
}

function parsePinnedMajor(value, label, applicationRoot) {
  const normalized = String(value || "").trim().replace(/^v/u, "");
  const match = normalized.match(/^(\d+)(?:\.x)?$/u);
  if (!match) {
    throw new ApplicationDocsInitError(
      `${label} must select one Node.js major such as 24 or 24.x; found ${JSON.stringify(normalized)}.`,
      { stage: "toolchain-preflight", applicationRoot },
    );
  }
  return Number(match[1]);
}

async function optionalFile(path) {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
}

async function pathExists(path) {
  try {
    await lstat(path);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

async function assertSafeApplicationPath(applicationRoot, target, stage) {
  const relativePath = relative(applicationRoot, target);
  if (!relativePath || relativePath === ".." || relativePath.startsWith(`..${sep}`)) {
    throw new ApplicationDocsInitError(`Unsafe application path: ${target}`, { stage, applicationRoot });
  }
  const segments = relativePath.split(sep);
  let current = applicationRoot;
  for (let index = 0; index < segments.length; index += 1) {
    current = join(current, segments[index]);
    let state;
    try {
      state = await lstat(current);
    } catch (error) {
      if (error?.code === "ENOENT") continue;
      throw error;
    }
    if (state.isSymbolicLink()) {
      throw new ApplicationDocsInitError(`Refusing to use a symbolic link during initialization: ${current}`, {
        stage,
        applicationRoot,
      });
    }
    if (index < segments.length - 1 && !state.isDirectory()) {
      throw new ApplicationDocsInitError(`Application path component is not a directory: ${current}`, {
        stage,
        applicationRoot,
      });
    }
  }
}

async function resolveApplicationRoot(applicationDir) {
  const target = resolve(applicationDir);
  let targetState;
  try {
    targetState = await stat(target);
  } catch (error) {
    throw new ApplicationDocsInitError(`Application directory does not exist: ${target}`, {
      stage: "application-root-preflight",
      applicationRoot: target,
      cause: error,
    });
  }
  if (!targetState.isDirectory()) {
    throw new ApplicationDocsInitError(`Application path is not a directory: ${target}`, {
      stage: "application-root-preflight",
      applicationRoot: target,
    });
  }
  return realpath(target);
}

async function readManifest(applicationRoot) {
  const path = join(applicationRoot, "package.json");
  await assertSafeApplicationPath(applicationRoot, path, "application-manifest-preflight");
  let source;
  try {
    source = await readFile(path, "utf8");
  } catch (error) {
    throw new ApplicationDocsInitError(`Application root must contain package.json: ${applicationRoot}`, {
      stage: "application-manifest-preflight",
      applicationRoot,
      cause: error,
    });
  }
  try {
    return { manifest: JSON.parse(source), path, source };
  } catch (error) {
    throw new ApplicationDocsInitError(`Application package.json is not valid JSON: ${error.message}`, {
      stage: "application-manifest-preflight",
      applicationRoot,
      cause: error,
    });
  }
}

async function assertNpmApplication(applicationRoot) {
  const requiredLock = join(applicationRoot, "package-lock.json");
  await assertSafeApplicationPath(applicationRoot, requiredLock, "package-manager-preflight");
  try {
    const state = await stat(requiredLock);
    if (!state.isFile()) throw new Error("not a regular file");
  } catch (error) {
    throw new ApplicationDocsInitError(
      "Documented Command Center applications require a root package-lock.json.",
      { stage: "package-manager-preflight", applicationRoot, cause: error },
    );
  }
  for (const name of ["yarn.lock", "pnpm-lock.yaml", "bun.lock", "bun.lockb"]) {
    if (await pathExists(join(applicationRoot, name))) {
      throw new ApplicationDocsInitError(
        `Remove the conflicting root package-manager lockfile before initialization: ${name}`,
        { stage: "package-manager-preflight", applicationRoot },
      );
    }
  }
}

async function prepareToolchain(applicationRoot, manifest) {
  const pins = [];
  for (const name of [".node-version", ".nvmrc"]) {
    const pinPath = join(applicationRoot, name);
    await assertSafeApplicationPath(applicationRoot, pinPath, "toolchain-preflight");
    const source = await optionalFile(pinPath);
    if (source !== null) pins.push({ name, major: parsePinnedMajor(source, name, applicationRoot) });
  }
  const engineValue = manifest?.engines?.node;
  const engineMajor = engineValue
    ? parsePinnedMajor(engineValue, "package.json engines.node", applicationRoot)
    : null;
  const declaredMajors = new Set([
    ...pins.map(({ major }) => major),
    ...(engineMajor === null ? [] : [engineMajor]),
  ]);
  if (declaredMajors.size > 1) {
    throw new ApplicationDocsInitError(
      `Node.js declarations disagree: ${[...declaredMajors].join(", ")}.`,
      { stage: "toolchain-preflight", applicationRoot },
    );
  }
  const runningMajor = Number(process.versions.node.split(".")[0]);
  const expectedMajor = [...declaredMajors][0] ?? runningMajor;
  if (expectedMajor < 20 || expectedMajor % 2 !== 0) {
    throw new ApplicationDocsInitError(
      `Documentation tooling requires an even-numbered Node.js LTS major at or above 20; found ${expectedMajor}.`,
      { stage: "toolchain-preflight", applicationRoot },
    );
  }
  if (runningMajor !== expectedMajor) {
    throw new ApplicationDocsInitError(
      `Run this command with Node.js ${expectedMajor}; the current runtime is ${process.versions.node}.`,
      { stage: "toolchain-preflight", applicationRoot },
    );
  }
  if (manifest.packageManager && !String(manifest.packageManager).startsWith("npm@")) {
    throw new ApplicationDocsInitError(
      `package.json packageManager must select npm when package-lock.json is authoritative; found ${manifest.packageManager}.`,
      { stage: "package-manager-preflight", applicationRoot },
    );
  }
  return {
    expectedMajor,
    createNodeVersion: pins.length === 0,
    addEngine: engineMajor === null,
  };
}

async function listTemplateFiles(directory = templateRoot) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (ignoredDirectories.has(entry.name)) continue;
    const path = join(directory, entry.name);
    if (entry.isSymbolicLink()) {
      throw new ApplicationDocsInitError(`Documentation template may not contain symbolic links: ${path}`, {
        stage: "template-preflight",
      });
    }
    if (entry.isDirectory()) files.push(...(await listTemplateFiles(path)));
    else if (entry.isFile()) files.push(path);
  }
  return files.sort();
}

function ensureManifestSlot(manifest, key) {
  if (manifest[key] === undefined) manifest[key] = {};
  if (!manifest[key] || typeof manifest[key] !== "object" || Array.isArray(manifest[key])) {
    throw new ApplicationDocsInitError(`package.json ${key} must be an object.`, {
      stage: "application-manifest-preflight",
    });
  }
  return manifest[key];
}

function setExactValue(target, key, value, label, applicationRoot) {
  if (target[key] !== undefined && target[key] !== value) {
    throw new ApplicationDocsInitError(
      `${label}.${key} already exists with a different value; preserve it and integrate documentation deliberately.`,
      { stage: "application-manifest-preflight", applicationRoot },
    );
  }
  target[key] = value;
}

function prepareManifest(original, toolchain, applicationRoot) {
  const manifest = structuredClone(original);
  const scripts = ensureManifestSlot(manifest, "scripts");
  if (typeof scripts.build !== "string" || !scripts.build.trim()) {
    throw new ApplicationDocsInitError(
      "package.json must declare the application build script before documentation is initialized.",
      { stage: "application-manifest-preflight", applicationRoot },
    );
  }
  if (scripts.build !== COMBINED_BUILD_SCRIPT) {
    if (scripts["build:app"] === undefined) scripts["build:app"] = scripts.build;
    scripts.build = COMBINED_BUILD_SCRIPT;
  }
  if (typeof scripts["build:app"] !== "string" || !scripts["build:app"].trim()) {
    throw new ApplicationDocsInitError(
      "package.json must retain a non-empty build:app script for the application artifact.",
      { stage: "application-manifest-preflight", applicationRoot },
    );
  }
  for (const [name, value] of Object.entries(DOCUMENTATION_SCRIPTS)) {
    setExactValue(scripts, name, value, "scripts", applicationRoot);
  }
  const dependencies = ensureManifestSlot(manifest, "devDependencies");
  for (const [name, value] of Object.entries(DOCUMENTATION_DEV_DEPENDENCIES)) {
    for (const section of ["dependencies", "optionalDependencies", "peerDependencies"]) {
      if (manifest?.[section]?.[name] !== undefined) {
        throw new ApplicationDocsInitError(
          `${name} is already declared in ${section}; documentation tooling must live in devDependencies.`,
          { stage: "application-manifest-preflight", applicationRoot },
        );
      }
    }
    setExactValue(dependencies, name, value, "devDependencies", applicationRoot);
  }
  if (toolchain.addEngine) {
    const engines = ensureManifestSlot(manifest, "engines");
    engines.node = `${toolchain.expectedMajor}.x`;
  }
  return manifest;
}

async function prepareFileWrites(applicationRoot, templateFiles) {
  const writes = [];
  const unchanged = [];
  const scaffoldPackageRelativePath = "documentation/package.json";
  const scaffoldPackageSource = templateFiles.find(
    (source) => relative(templateRoot, source) === scaffoldPackageRelativePath,
  );
  const scaffoldPackageContent = scaffoldPackageSource
    ? await readFile(scaffoldPackageSource, "utf8")
    : null;
  await assertSafeApplicationPath(
    applicationRoot,
    join(applicationRoot, scaffoldPackageRelativePath),
    "template-preflight",
  );
  const scaffoldManaged =
    scaffoldPackageContent !== null &&
    (await optionalFile(join(applicationRoot, scaffoldPackageRelativePath))) === scaffoldPackageContent;
  for (const source of templateFiles) {
    const relativePath = relative(templateRoot, source);
    if (
      !relativePath ||
      relativePath === ".." ||
      relativePath.startsWith(`..${sep}`)
    ) {
      throw new ApplicationDocsInitError(`Unsafe documentation template path: ${source}`, {
        stage: "template-preflight",
        applicationRoot,
      });
    }
    const destination = join(applicationRoot, relativePath);
    await assertSafeApplicationPath(applicationRoot, destination, "template-preflight");
    const content = await readFile(source, "utf8");
    const existing = await optionalFile(destination);
    if (existing === null) writes.push({ destination, relativePath, content });
    else if (existing === content) unchanged.push(relativePath);
    else if (
      existing.startsWith(generatedTemplateMarkers.get(relativePath) || "\0") ||
      (scaffoldManaged &&
        (relativePath.startsWith("docs/") ||
          new Set([
            "documentation/navigation.json",
            "documentation/sidebars.mjs",
          ]).has(relativePath)))
    ) {
      unchanged.push(relativePath);
    } else {
      throw new ApplicationDocsInitError(
        `Refusing to overwrite existing documentation file: ${relativePath}`,
        { stage: "template-conflict", applicationRoot },
      );
    }
  }
  return { writes, unchanged };
}

async function prepareGitignore(applicationRoot) {
  const path = join(applicationRoot, ".gitignore");
  await assertSafeApplicationPath(applicationRoot, path, "template-preflight");
  const existing = (await optionalFile(path)) ?? "";
  const additions = ["documentation/.docusaurus/", "dist/"];
  const lines = new Set(existing.split(/\r?\n/u).map((line) => line.trim()));
  const missing = additions.filter((line) => !lines.has(line));
  if (missing.length === 0) return { path, content: existing, changed: false };
  const prefix = existing && !existing.endsWith("\n") ? `${existing}\n` : existing;
  return { path, content: `${prefix}${missing.join("\n")}\n`, changed: true };
}

async function writePreparedFile({ destination, content }) {
  await mkdir(dirname(destination), { recursive: true });
  const parent = await lstat(dirname(destination));
  if (parent.isSymbolicLink()) {
    throw new ApplicationDocsInitError(`Refusing to write through a symbolic-link directory: ${dirname(destination)}`, {
      stage: "template-write",
    });
  }
  await writeFile(destination, content, "utf8");
}

function installDependencies(applicationRoot, { quiet, spawnSyncImpl, processEnv }) {
  const result = spawnSyncImpl("npm", ["install"], {
    cwd: applicationRoot,
    encoding: "utf8",
    stdio: quiet ? "pipe" : "inherit",
    env: { ...processEnv, COMMAND_CENTER_SDK_MCP_POSTINSTALL: "0" },
  });
  if (result.error || result.status !== 0) {
    const detail = String(result.stderr || result.stdout || result.error?.message || "").trim();
    throw new ApplicationDocsInitError(
      `Documentation files were created, but npm install failed${detail ? `: ${detail.slice(0, 1_000)}` : "."}`,
      { stage: "dependency-install", applicationRoot, cause: result.error },
    );
  }
}

export async function initializeApplicationDocumentation({
  applicationDir = process.cwd(),
  dryRun = false,
  install = true,
  quiet = false,
  spawnSyncImpl = spawnSync,
  processEnv = process.env,
} = {}) {
  const applicationRoot = await resolveApplicationRoot(applicationDir);
  await assertNpmApplication(applicationRoot);
  const { manifest: originalManifest, path: packageJsonPath } = await readManifest(applicationRoot);
  const toolchain = await prepareToolchain(applicationRoot, originalManifest);
  const manifest = prepareManifest(originalManifest, toolchain, applicationRoot);
  const templateFiles = await listTemplateFiles();
  const preparedFiles = await prepareFileWrites(applicationRoot, templateFiles);
  const gitignore = await prepareGitignore(applicationRoot);
  const packageContent = `${JSON.stringify(manifest, null, 2)}\n`;
  const existingPackageContent = await readFile(packageJsonPath, "utf8");
  const packageChanged = existingPackageContent !== packageContent;
  const nodeVersionPath = join(applicationRoot, ".node-version");
  await assertSafeApplicationPath(applicationRoot, nodeVersionPath, "toolchain-preflight");
  const nodeVersionWrite = toolchain.createNodeVersion
    ? { destination: nodeVersionPath, relativePath: ".node-version", content: `${toolchain.expectedMajor}\n` }
    : null;
  const created = [
    ...preparedFiles.writes.map(({ relativePath }) => relativePath),
    ...(nodeVersionWrite ? [nodeVersionWrite.relativePath] : []),
  ];
  const updated = [
    ...(packageChanged ? ["package.json"] : []),
    ...(gitignore.changed ? [".gitignore"] : []),
  ];
  const commands = install ? ["npm install"] : [];

  if (!dryRun) {
    for (const item of preparedFiles.writes) await writePreparedFile(item);
    if (nodeVersionWrite) await writePreparedFile(nodeVersionWrite);
    if (packageChanged) await writeFile(packageJsonPath, packageContent, "utf8");
    if (gitignore.changed) await writeFile(gitignore.path, gitignore.content, "utf8");
    if (install) installDependencies(applicationRoot, { quiet, spawnSyncImpl, processEnv });
  }

  return {
    applicationRoot,
    dryRun,
    installed: !dryRun && install,
    nodeMajor: toolchain.expectedMajor,
    docsBaseUrl: "/docs/",
    created,
    updated,
    unchanged: preparedFiles.unchanged,
    commands,
    next: [
      ...(install ? [] : ["npm install"]),
      "npm run docs:check",
      "npm run build",
      "run the application's production-artifact browser suite for /docs/ and a nested route",
    ],
  };
}
